#配置文件加载顺序: logback.xml--->application.properties--->logback-spring.xml
server:
  port: 3002
  tomcat:
    basedir: /opt/services/xiu/xiu-service
    accesslog:
      enabled: true
      directory: logs
eureka:
  instance:
    #将IP注册到Eureka Server上，而如果不配置就是机器的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://vick:success@localhost:3000/eureka/
logging:
  #logging.level.root的级别会覆盖logback-spring.xml中定义的root的级别
  #logback-spring.xml会覆盖logging.file.path 所以要集中到一处进行配置
  #file:
    #path: logs/xiu-service
  level:
    #root: INFO
    #swagger日志级别
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
  config: classpath:logback-spring-${spring.profiles.active}.xml
spring:
  application:
    name: xiu-service
  #数据源配置信息
  datasource:
    #数据源基本配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiu?useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: success
    #druid连接池特定配置
    druid:
      ## 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      ## 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        #是否能够重置数据
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        allow: 127.0.0.1
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        enabled: false
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
    #定时任务配置信息
  quartz:
   auto-startup: true
mybatis-plus:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
  global-config:
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
  #打印SQL
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger2:
  #开发环境用true，生产环境上禁止swagger，用false
  enable: false