#配置文件加载顺序: logback.xml--->application.properties--->logback-spring.xml
server:
  port: 3002
  tomcat:
    basedir: /opt/services/xiu/xiu-service
    accesslog:
      enabled: true
      directory: logs
logging:
  #logging.level.root的级别会覆盖logback-spring.xml中定义的root的级别
  #logback-spring.xml会覆盖logging.file.path 所以要集中到一处进行配置
  #file:
    #path: logs/xiu-service
  level:
    #root: INFO
    #swagger日志级别
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
  config: classpath:logback-spring-${spring.profiles.active}.xml
spring:
  application:
    name: xiu-service
  #数据源配置信息
  datasource:
    #数据源基本配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiu?useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: success
    #druid连接池特定配置
    ## 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis-plus:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
  global-config:
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
  #打印SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger2:
  #开发环境用true，生产环境上禁止swagger，用false
  enable: true