server:
  port: 3000
  tomcat:
    basedir: /opt/services/xiu/xiu-register
    accesslog:
      enabled: true
      directory: logs
# 设置是否将自己作为客户端注册到注册中心（缺省true）
# 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: xiu-regisger
logging:
  file:
    name: ${server.tomcat.basedir}/logs/${spring.application.name}.log
  config: classpath:logback-${spring.profiles.active}.xml
